### ISSUE TITLE
Allow Setting `AutoTopicCreation` on Pulsar Namespace Resources

### ISSUE THREAD

**Issue by asher-goldberg** [streamnative/terraform-provider-pulsar#111]
### Community Note

* Please vote on this issue by adding a
  👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original
  issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra
  noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to be able to set/override/remove auto topic creation through the namespace policies when adding a namespace resource via TF.  We set this at the broker level but there are some namespace we don't want it on.

### New or Affected Resource(s)

* pulsar_namespace

### Potential Terraform Configuration

I think the clearest way to do this is as a separate object within the resource like the retention and persistent policy blocks.  The three keys below match what the admin client requires.

```hcl
resource "pulsar_namespace" "namespace" {
  tenant = "public"
  namespace = "test"

  topic_auto_creation {
    allow = true
    type = "partitioned"
    partitions = 3
  } 
}
```

```hcl
resource "pulsar_namespace" "namespace" {
  tenant = "public"
  namespace = "test"

  topic_auto_creation {
    allow = false
  } 
}
```

If `allow` is set to `false` then `type` and `partitions` should be optional.

**Comment by jiangpengcheng** [comment]
The underlying library(pulsar-admin-go) doesn't expose the `GetTopicAutoCreation` yet, so I created a PR here: https://github.com/apache/pulsar-client-go/pull/1151

will add topic auto-creation in this repo after the above PR is merged
