### ISSUE TITLE
Topic not found error raised when setting retention policies on multiple topics

### ISSUE THREAD

**Issue by esenac** [streamnative/terraform-provider-pulsar#48]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.1.2

### Affected Resource(s)

* pulsar_topics

### Terraform Configuration Files

An example can be found [here](https://github.com/esenac/pulsar-terraform-examples/tree/topic-not-found-error)

### Debug Output

https://gist.github.com/esenac/097a3bba59f36e169c6f8b378ed91da9

### Expected Behavior

Topic retention policies (the default ones in this case) are correctly set on the topics after the topics have successfully been created.

### Actual Behavior

Topic level retention policies are not set because the declared topics seem not to exist on Pulsar even if they're in the same Terraform file.

### Steps to Reproduce

1. Declare a list of topics 
2. Loop the list to create topics resources in Terraform
3. `terraform apply`

### Important Factoids

The issue does not occur with a reduced amount of topics in the list.

**Comment by nodece** [comment]
@esenac can #47 fix this issue?

**Comment by esenac** [comment]
@nodece not in the case we try to set policies to each topic, because the calls would be made and they would cause the "concurrency" problem.

**Comment by nodece** [comment]
@esenac I will work on this tomorrow.

**Comment by nodece** [comment]
@esenac I tried to run your project with the latest terraform-provider-pulsar, and it is working, the following is my log:
```
[+] Building 34.2s (16/16) FINISHED                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 2B                                                                                                              0.0s
 => [internal] load metadata for docker.io/apachepulsar/pulsar:2.7.3                                                                         1.8s
 => [internal] load metadata for docker.io/library/debian:stretch-slim                                                                       1.9s
 => [tf 1/3] FROM docker.io/library/debian:stretch-slim@sha256:5913f0038562c1964c62fc1a9fcfff3c7bb340e2f5dbf461610ab4f802368eee              0.0s
 => [stage-1 1/7] FROM docker.io/apachepulsar/pulsar:2.7.3@sha256:f858f9535668032db9d18c33b398b60a678696b944241c5213e4466f46c18fa7           0.0s
 => [internal] load build context                                                                                                            0.6s
 => => transferring context: 25.71MB                                                                                                         0.5s
 => CACHED [tf 2/3] RUN ARCH=$(if [ $(uname -m) = "aarch64" ]; then echo "arm64"; else echo "amd64"; fi) &&     apt-get update && apt-get i  0.0s
 => CACHED [tf 3/3] RUN chmod +x terraform                                                                                                   0.0s
 => CACHED [stage-1 2/7] COPY --from=tf terraform /bin/terraform                                                                             0.0s
 => [stage-1 3/7] COPY ./terraform-pulsar-plugin terraform.d/                                                                                0.2s
 => [stage-1 4/7] COPY ./*.tf ./                                                                                                             0.0s
 => [stage-1 5/7] COPY wait-for-it-api.sh ./                                                                                                 0.0s
 => [stage-1 6/7] COPY ./conf/standalone.conf /pulsar/conf/standalone.conf                                                                   0.0s
 => [stage-1 7/7] RUN ./bin/pulsar standalone > /dev/null &     export PROCESS_ID=$! &&     terraform init &&     ./wait-for-it-api.sh htt  31.0s
 => exporting to image                                                                                                                       0.4s
 => => exporting layers                                                                                                                      0.4s
 => => writing image sha256:2da0eb11693b1f5436375b7365042d59c535c607c5b2d3b0b1e3712f66c1f9fd                                                 0.0s 
 => => naming to docker.io/library/pulsar-examples                                                                                           0.0s 
                                                                                                                                                  
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them           
```

**Comment by esenac** [comment]
@nodece I've updated the provider and added retention policies to the topics in [this commit](https://github.com/esenac/pulsar-terraform-examples/commit/eeba742e7d50128b93cfb6e8cc98ea8381efbe65), which led to the error. I've updated the examples repo accordingly on the `topic-not-found-error` branch.

**Comment by nodece** [comment]
The issue can be reproduced locally, but it can work on Pulsar 2.9, @esenac Should I add a loop to check whether the topic exists?

**Comment by esenac** [comment]
@nodece yes I would go with a fix as we can not easily upgrade to Pulsar 2.9.

**Comment by nodece** [comment]
I submitted #50 to fix this, could you take a look?

**Comment by nodece** [comment]
@codelipenghui Do you have any ideas to fix this?

**Comment by esenac** [comment]
@nodece is there any update on this?

**Comment by nodece** [comment]
@esenac Please wait for others to review.
