### ISSUE TITLE
Setting persistence_policy with no value result in a default of 0 being applied

### ISSUE THREAD

**Issue by martijngonlag** [streamnative/terraform-provider-pulsar#72]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v1.3.6
on darwin_amd64
```

### Affected Resource(s)

* `persistence_policies`

### Terraform Configuration Files

```hcl
persistence_policies {
bookkeeper_ensemble =
each.value["bookkeeper_ensemble"]
// Number of bookies to use for a topic, default: 0

bookkeeper_write_quorum =
each.value["bookkeeper_write_quorum"]
// How many writes to make of each entry, default: 0

bookkeeper_ack_quorum =
each.value["bookkeeper_ack_quorum"]
// Number of acks (guaranteed copies) to wait for each entry, default: 0

managed_ledger_max_mark_delete_rate
= each.value["managed_ledger_max_mark_delete_rate"]
// Throttling rate of mark-delete operation (0 means no throttle), default: 0.0
}
```

### Expected Behavior

When no values are specified for `bookkeeper_ensemble`, `bookkeeper_write_quorum`, `bookkeeper_ack_quorum` and `managed_ledger_max_mark_delete_rate`, the value for each parameter should be `null`.

### Actual Behavior

When no values are specified for `bookkeeper_ensemble`, `bookkeeper_write_quorum`, `bookkeeper_ack_quorum` and `managed_ledger_max_mark_delete_rate`, the value for each parameter is `0`. As a result, when this is applied, producers cannot produce messages into the Pulsar cluster.

### Steps to Reproduce

1. `terraform apply` the above configuration

### Important Factoids

* This is also incorrect in the Pulsar docs, where the default for `bookkeeper_ensemble`, `bookkeeper_write_quorum`, `bookkeeper_ack_quorum` and `managed_ledger_max_mark_delete_rate` is listed as `0`.

**Comment by gengmao** [comment]
@maxsxu can you please take care of this request?

**Comment by maxsxu** [comment]
@martijngonlag How's your `for_each` is defined?

Tested below 2 cases:

- Without `persistence_policies` block

```hcl
resource "pulsar_namespace" "ns-1" {
  namespace = "ns-1"
  tenant = "public"
}
```

Will create public/ns-1 successfully, and the output of `pulsar-admin namespaces get-persistence public/ns-1` is `null`.
And message produce/consume is healthy.

- An empty`persistence_policies` block

```hcl
resource "pulsar_namespace" "ns-2" {
  namespace = "ns-2"
  tenant = "public"

  persistence_policies {
  }
}
```

Will throw error 

```
╷
│ Error: Missing required argument
│ 
│   on main.tf line 10, in resource "pulsar_namespace" "ns-2":
│   10:   persistence_policies {
│ 
│ The argument "bookkeeper_ensemble" is required, but no definition was found.
╵
```

That's expected as we marked the elements as required in `persistence_policies` block.

---

For Pulsar itself, I think this issue is fixed by https://github.com/apache/pulsar/pull/18999

And the latest Pulsar doc https://pulsar.apache.org/docs/next/admin-api-namespaces/#set-persistence-policies

> 
> Bookkeeper-ack-quorum: Number of acks (guaranteed copies) to wait for each entry, default: 2
> Bookkeeper-ensemble: Number of bookies to use for a topic, default: 2
> Bookkeeper-write-quorum: How many writes to make of each entry, default: 2
> Ml-mark-delete-max-rate: Throttling rate of mark-delete operation (0 means no throttle), default: 0
>

**Comment by martijngonlag** [comment]
@maxsxu the customers Terraform file is included in the original request, there was nothing else done.
