### ISSUE TITLE
400 Error when Updating Sinks and Sources with Terraform

### ISSUE THREAD

**Issue by asher-goldberg** [streamnative/terraform-provider-pulsar#90]
Terraform apply results in a `400 bad request` error when there are sinks/source present in the TF plan.  They will apply correctly the first time, but every subsequent run will result in a 400, even if no changes are planned for the resource.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform version 1.3.5
Pulsar provider version 0.1.3 (using v3 of API)

### Affected Resource(s)

* pulsar_sink
* pulsar_source

### Terraform Configuration Files

```hcl
provider "pulsar" {
  alias           = "pulsar-v3"
  web_service_url = local.pulsar_web_service_url
  token           = var.pulsar_token
  api_version     = "3"
}

resource "pulsar_source" "pulsar_sqs_fallback" {
  provider               = pulsar.pulsar-v3
  name                   = "sqs-test"
  tenant                 = "public"
  namespace              = "default"
  destination_topic_name = "sqs-source-connector-test"
  archive                = "builtin://sqs"
  classname              = "org.apache.pulsar.ecosystem.io.sqs.SQSSource"
  parallelism            = 1
  cpu                    = 1
  ram_mb                 = 1024
  disk_mb                = 10240
  configs = jsonencode({
    awsEndpoint             = "https://sqs.${data.aws_region.current.name}.amazonaws.com"
    awsRegion               = data.aws_region.current.name
    queueName               = test-queue
    batchSizeOfOnceReceive  = 10
    numberOfConsumers       = 10
    awsCredentialPluginName = "org.apache.pulsar.io.aws.STSAssumeRoleProviderPlugin"
    awsCredentialPluginParam = jsonencode({
      roleArn         = "arn:aws:iam::xxxxxxxxx:role/test-role"
      roleSessionName = "name"
    })
  })
}
```

### Expected Behavior

TF applies should work fine especially if no changes are being made to the sink/source.

### Actual Behavior

Any subsequent apply results in this error, even if there are no changes to the plan
```
│ Error: code: 400 reason: 400 Bad Request
│ 
│   with pulsar_sink.cloud_storage_sink,
│   on pulsar_sinks.tf line 11, in resource "pulsar_sink" "cloud_storage_sink":
│   11: resource "pulsar_sink" "cloud_storage_sink" {

│ Error: code: 400 reason: 400 Bad Request
│ 
│   with pulsar_source.pulsar_sqs_fallback,
│   on pulsar_sources.tf line 28, in resource "pulsar_source" "pulsar_sqs_fallback":
│   28: resource "pulsar_source" "pulsar_sqs_fallback" {
```

### Steps to Reproduce
1. `terraform apply` once to create a source or sinks - works successfully
2. `terraform apply` again - get 400 bad request

### References

* #0000

**Comment by nlu90** [comment]
This turns out to be a problem when running TF with a Pulsar-Proxy-enabled cluster.
For Istio-enabled clusters, it runs fine.
I'll close the issue for now.
